### ISSUE TITLE
Associations with models that dont have routing keys creates an error

### ISSUE THREAD

**Issue by ryanwilliamquinn** [tjwebb/sails-rabbitmq#3]
Storing a message works fine, but if the message has a file association, it creates this error:

```
/Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: The model filedescriptor_files_filedescriptor__message_files must define a routingKey
        in order to be used with the Waterline pubsub interface
    at Object.getRoutingKey (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-rabbitmq/dist/adapter.js:377:13)
    at Object.wrapper [as getRoutingKey] (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-rabbitmq/node_modules/lodash/index.js:3095:19)
    at Object.publish (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-rabbitmq/dist/adapter.js:249:27)
    at bound.wrapper (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-rabbitmq/node_modules/lodash/index.js:3095:19)
    at bound.self.(anonymous function) (/Users/rquinn/.nvm/versions/node/v0.12.5/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/adapters.js:35:29)
    at bound [as publish] (/Users/rquinn/.nvm/versions/node/v0.12.5/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/rquinn/repos/PathwaysAPI/node_modules/sails-rabbitmq/dist/handlers/persistence.js:73:26
    at /Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/lib/adapter.js:280:9
    at /Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/lib/collection.js:184:5
    at handleCallback (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:564:5
    at /Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:806:13
    at Callbacks.emit (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:23)
    at Socket.<anonymous> (/Users/rquinn/repos/PathwaysAPI/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)```

**Comment by tjwebb** [comment]
fixed in filemanager
